INSERT INTO Question (Type, Title) VALUES ("CLOSED_ONE", "What is the distance between the Earth and the Sun? (in meters)"),
    ("CLOSED_ONE", "What is the name of the nearest major galaxy to the Milky Way?"),
    ("CLOSED_ONE", "Which of the following is NOT a planet type?"),
    ("CLOSED_ONE", "What is the main compound of Jupiter?"),
    ("CLOSED_ONE", "What type of star is our Sun?"),
    ("CLOSED_ONE", "What is the brightest star in our sky?"),
    ("CLOSED_ONE", "Which one of these is a globular cluster?"),
    ("CLOSED_ONE", "What is the name of a failed star?"),
    ("CLOSED_ONE", "What is the main type of galaxy in the universe?"),
    ("CLOSED_ONE", "What is the place between stars called?"),
    ("CLOSED_ONE", "How long does it take for light from the Sun reach us on Earth?"),
    ("CLOSED_ONE", "How long does it take reflected sunlight from the Moon to reach us?"),
    ("CLOSED_ONE", "What is the largest moon in our solar system?"),
    ("CLOSED_ONE", "What arm of the galaxy is our solar system in?"),
    ("CLOSED_ONE", "What kind of spatial explosion is the advanced form of a supernova?"),
    ("CLOSED_ONE", "What is the furthest object visible to the naked eye on Earth?"),
    ("CLOSED_ONE", "What cluster is our galaxy in?"),
    ("CLOSED_ONE", "How is Einstein’s Cross created?"),
    ("CLOSED_ONE", "How many galaxies do scientists extimate are in the universe to date?"),
    ("CLOSED_ONE", "Hypothetically, not including things such as how the vacuum of space will kill a person in less than one minute, is it possible to get sucked into a black hole before dying?"),
    ("CLOSED_ONE", "What curiosity do astronomers believe are galaxies with extremely active super massive black holes at their centers that represent the state of all galaxies near the beginning of the universe?"),
    ("CLOSED_ONE", "What is the largest known galaxy in the universe?"),
    ("CLOSED_ONE", "What is the most massive known star in the universe?"),
    ("CLOSED_ONE", "What kind of nebulae are typically blue in color?"),
    ("CLOSED_MANY", "Which of these choices is a Kingdom?"),
    ("CLOSED_MANY", "Which of these is a term used in the classification of species?"),
    ("CLOSED_MANY", "Which of these words are associated with plants?"),
    ("CLOSED_MANY", "Angiosperms were the first plants to have…"),
    ("CLOSED_ONE", "What species of gymnosperm is the last of its kind in the division?"),
    ("CLOSED_ONE", "Which of these is NOT a system in your body?"),
    ("CLOSED_ONE", "Which are terms associated with cell division?"),
    ("CLOSED_ONE", "All plants have a vascular system of pipes that transport fluids."),
    ("CLOSED_ONE", "All plants except mosses produce seeds."),
    ("CLOSED_ONE", "Plants reproduce asexually"),
    ("CLOSED_ONE", "Which of these plants requires water to reproduce?"),
    ("CLOSED_ONE", "The big advantage of gymnosperms over the ferns is that…"),
    ("CLOSED_ONE", "What words describe the basic structures of vascular plants?"),
    ("CLOSED_MANY", "Which of the following elements are liquids around room temperature?"),
    ("CLOSED_MANY", "Which of the following are amino acids?"),
    ("CLOSED_ONE", "One of the essential minerals in the human body is salt. How much salt (NaCl) is in the average adult human body?"),
    ("CLOSED_ONE", "If you fill a glass to the brim with ice water and the ice melts, what will happen?"),
    ("CLOSED_ONE", "The symbol Sb stands for stibnum or stibnite. What is the modern name of this element?"),
    ("CLOSED_ONE", "Water-based liquids can be described as acidic, neutral, or basic, with respect to pH. Which of these describes milk?"),
    ("CLOSED_ONE", "DNA codes for proteins, which are the building blocks of organisms. What is the most abundant protein in the human body?"),
    ("CLOSED_ONE", "Noble gases are inert because they have completed outer electron shells. Which of these elements isn't a noble gas?"),
    ("CLOSED_ONE", "What is the most common isotope of hydrogen?"),
    ("CLOSED_ONE", "You can’t live without water! What is its chemical formula?"),
    ("CLOSED_ONE", "Who is credited with the invention of the modern periodic table?"),
    ("CLOSED_ONE", "Which of these elements is a nonmetal?"),
    ("CLOSED_ONE", "Organic chemistry is the study of the compounds that make up living organisms. All organic molecules contain:"),
    ("CLOSED_ONE", "The symbol Ag stands for which element?"),
    ("CLOSED_ONE", "Three of the most common states of matter are solids, liquids, and gases. A liquid has:"),
    ("CLOSED_ONE", "Where in the body is the most of the iron located?"),
    ("CLOSED_ONE", "What is Avogadro's number?"),
    ("CLOSED_ONE", "What do you call an atom that has more protons than electrons?"),
    ("CLOSED_ONE", "A drop of blood coloring spreading out in a cup of water is and example of which transport process?"),
    ("CLOSED_ONE", "In a saline solution salt is the:"),
    ("CLOSED_ONE", "Magyars are the people of which country?"),
    ("CLOSED_ONE", "Pilbara is a region in which Australian state?"),
    ("CLOSED_ONE", "What is the capital of Armenia?"),
    ("CLOSED_ONE", "The Chukchi Sea is north of which sea?"),
    ("CLOSED_ONE", "Where is the Levantine Basin found?"),
    ("CLOSED_ONE", "The Chalbi Desert and Cherangay Hills are found in which county?"),
    ("CLOSED_ONE", "Which country occupies most of Cisjordan?"),
    ("CLOSED_ONE", "The Baikonur Cosmodrome, Russia's main space launch facility, is located in which country?"),
    ("CLOSED_ONE", "Lebanon gained independence from which country in 1943?"),
    ("CLOSED_ONE", "The TauTona Gold Mine is the world's deepest mine; in which country can it be found?"),
    ("CLOSED_ONE", "Rarotonga is an island in which country?"),
    ("CLOSED_ONE", "The border between Wales and England lies near which line on longitude?"),
    ("CLOSED_ONE", "The Isles of Sicilly are an archipelago off the tip of which cape?"),
    ("CLOSED_ONE", "Within which country can two other independent countries be found?"),
    ("CLOSED_ONE", "The Electoral Palatinate was a historic region along which river?"),
    ("CLOSED_ONE", "For what plantation crop did Boston minister Increase Mather name his son?"),
    ("CLOSED_ONE", "Physicist Robert Oppenheimer was the head of what 1950s government initiative?"),
    ("CLOSED_ONE", "Which religious group, now known as 'pilgrims', settled Plymouth Colony?"),
    ("CLOSED_ONE", "John Tyler succeeded which of the following U.S. presidents?"),
    ("CLOSED_ONE", "To which island did the French government grant greater autonomy in 2000?"),
    ("CLOSED_ONE", "Which Soviet leader is known for the reform concepts of 'perestroika' and 'glasnost'?"),
    ("CLOSED_ONE", "What ancient civilization, famous for pharoahs and pyramids, was also renowned for brewing massive quantities of beer?"),
    ("CLOSED_ONE", "India won independence in 1947. The man behind it was shot dead the following year. Who was it?"),
    ("CLOSED_ONE", "Who was the Carthaginian general who led an army with elephants from Spain to northern Italy to attack Rome, in 218 BC?"),
    ("CLOSED_ONE", "Which British commander surrendered to George Washington in 1781?"),
    ("CLOSED_ONE", "From which colonial power did Argentina declare its independence on July 9 1816?"),
    ("CLOSED_ONE", "World War I began in which year?"),
    ("CLOSED_ONE", "Adolf Hitler was born in which country?"),
    ("CLOSED_ONE", "John F. Kennedy was assassinated in"),
    ("CLOSED_ONE", "Who fought in the war of 1812?"),
    ("CLOSED_ONE", "Which general famously stated 'I shall return'?"),
    ("CLOSED_ONE", "American involvement in the Korean War took place in which decade?"),
    ("CLOSED_ONE", "The Battle of Hastings in 1066 was fought in which country?"),
    ("CLOSED_ONE", "The Magna Carta was published by the King of which country?"),
    ("CLOSED_ONE", "The first successful printing press was developed by this man."),
    ("CLOSED_ONE", "The disease that ravaged and killed a third of Europe's population in the 14th century is known as"),
    ("CLOSED_ONE", "The Hundred Years War was fought between what two countries?"),
    ("CLOSED_ONE", "Which Roman Emperor built a massive wall across Northern Britain in 122 A.D.?"),
    ("CLOSED_ONE", "This man wrote a document known as the 95 Theses."),
    ("CLOSED_ONE", "In 1594 William Shakespeare joined the company of this London theatre."),
    ("CLOSED_ONE", "The Khmer Rouge was a regime ruling this nation in the 20th century."),
    ("CLOSED_ONE", "What famous 5th century A.D conqueror was known as 'The Scourge of God'?"),
    ("CLOSED_ONE", "Who was the first Western explorer to reach China?"),
    ("CLOSED_ONE", "189 + 712 ="),
    ("CLOSED_ONE", "Speed of a car is 60 km/hr. Distance covered in 1 ¼ hours is"),
    ("CLOSED_ONE", "What is an imaginary number?"),
    ("CLOSED_ONE", "13 * 14 ="),
    ("CLOSED_ONE", "What is the equation for the circumference of a circle?"),
    ("CLOSED_ONE", "What is the cube root of 125?"),
    ("CLOSED_ONE", "19 + … = 42"),
    ("CLOSED_ONE", "What is the symbol of pi?"),
    ("CLOSED_ONE", "A long rope has to be cut to make 23 small pieces. If it is double folded to start with how many times does it need to be cut?"),
    ("CLOSED_ONE", "How many lines can be drawn through two points?"),
    ("CLOSED_ONE", "1010 gram = ……… kg"),
    ("CLOSED_ONE", "Average of three person’s age is 9 years. Find the sum of there age."),
    ("CLOSED_MANY", "Mark the prime numbers"),
    ("CLOSED_ONE", "Who sings the song 'The Climb', from the film 'Hannah Montana: The Movie'?"),
    ("CLOSED_ONE", "In a song performed by Three Dog Night, which number is 'the loneliest number that you'll ever do'?"),
    ("CLOSED_ONE", "The singing of Enya, Annie Lennox, Emilíana Torrini and boy soprano, Ben Del Maestro, were all featured in what blockbuster trilogy's soundtrack?"),
    ("CLOSED_ONE", "What are the small metal bars which run perpendicular to a guitar's neck called?"),
    ("CLOSED_ONE", "Which Oklahoman was 'Bound for Glory' and wrote a song known by most school children ('This Land Is Your Land')?"),
    ("CLOSED_ONE", "Uillean, Northumbrian, and Great Highland are all types of this wind instrument."),
    ("CLOSED_ONE", "When playing the guitar, which of these methods is NOT a typical way of striking the strings?"),
    ("CLOSED_ONE", "Charli XCX collaborates with who for the song 'Fancy'?"),
    ("CLOSED_ONE", "Complete the sentence from the song 'Blank Space': Boys only one love if it's…"),
    ("CLOSED_ONE", "Who sang: Lips are movin?"),
    ("CLOSED_ONE", "Who wrote the song 'Black Widow'?"),
    ("CLOSED_ONE", "Which song did Selena Gomez sing?"),
    ("CLOSED_MANY", "Kanye West interrupted music industry award ceremonies in 2009 and 2015 to protest the choice of winner. Who were the artists affected?"),
    ("CLOSED_MANY", "Who sang 'Bang bang'?"),
    ("CLOSED_MANY", "Who sang 'Uptown Funk'?"),
    ("CLOSED_ONE", "If an object is in motion, what kind of energy does it posses?"),
    ("CLOSED_ONE", "What is the force that holds back a sliding object?"),
    ("CLOSED_ONE", "What is the applied force needed to move an object?"),
    ("CLOSED_ONE", "What property causes a moving object to continue moving?"),
    ("CLOSED_MANY", "One calorie is equal to the energy needed to increase one gram of water by one degree"),
    ("CLOSED_ONE", "At what temperature Fahrenheit does water boil?"),
    ("CLOSED_ONE", "The amount of matter in an object is its"),
    ("CLOSED_ONE", "Force is measured by what unit of measure?"),
    ("CLOSED_ONE", "Who developed the original idea of atoms?"),
    ("CLOSED_ONE", "What does the C stand for in the equation E=mc^2?"),
    ("CLOSED_ONE", "What is the force that keeps us on the ground?"),
    ("CLOSED_ONE", "Who developed Calculus as a result of his work in Physics?"),
    ("CLOSED_MANY", "Which particles are found in the nucleus of an atom?"),
    ("CLOSED_MANY", "Energy is measured in what unit of measurement?"),
    ("CLOSED_ONE", "An object at rest maintains what type of energy?"),
    ("CLOSED_ONE", "The do...while loop is ideal for loop structures that"),
    ("CLOSED_ONE", "What is computer programming?"),
    ("CLOSED_ONE", "Which of these are programming languages?"),
    ("CLOSED_ONE", "Which of the following is NOT a web language?"),
    ("CLOSED_ONE", "Ask user for a number, ask user for another number, multiply the two numbers, print result. What do you call this set of instructions?"),
    ("CLOSED_ONE", "What is the software called that translates code into something the computer can understand?"),
    ("CLOSED_ONE", "If you needed to execute some code repeatedly based on a certain condition, which of the following would you certainly use?"),
    ("CLOSED_ONE", "Imagine a car as a computer, and its engine as a program. Which of the following is an input for the engine program?"),
    ("CLOSED_ONE", "Why was the language called 'Python'?"),
    ("CLOSED_ONE", "Which tag may be used to indicate a comment in your PHP code?"),
    ("CLOSED_ONE", "To add 1 to the variable $myNum, use the following:"),
    ("CLOSED_ONE", "What is email spoofing?"),
    ("CLOSED_MANY", "Which of the following statements about methods are true?");

INSERT INTO Categories (Name) VALUES ("Astronomy"),
("Biology"),
("Chemistry"),
("Geography"),
("History"),
("Maths"),
("Music"),
("Physics"),
("Programming");

INSERT INTO Stages(CategoryId, Number) VALUES (1, 1),
(2, 1),
(3, 1),
(4, 1),
(5, 1),
(6, 1),
(7, 1),
(8, 1),
(9, 1);

INSERT INTO QuestionCategories (QuestionId, CategoryId) VALUES (1, 1),
(2, 1),
(3, 1),
(4, 1),
(5, 1),
(6, 1),
(7, 1),
(8, 1),
(9, 1),
(10, 1),
(11, 1),
(12, 1),
(13, 1),
(14, 1),
(15, 1),
(16, 1),
(17, 1),
(18, 1),
(19, 1),
(20, 1),
(21, 1),
(22, 1),
(23, 1),
(24, 1),
(25, 2),
(26, 2),
(27, 2),
(28, 2),
(29, 2),
(30, 2),
(31, 2),
(32, 2),
(33, 2),
(34, 2),
(35, 2),
(36, 2),
(37, 2),
(38, 3),
(39, 3),
(40, 3),
(41, 3),
(42, 3),
(43, 3),
(44, 3),
(45, 3),
(46, 3),
(47, 3),
(48, 3),
(49, 3),
(50, 3),
(51, 3),
(52, 3),
(53, 3),
(54, 3),
(55, 3),
(56, 3),
(57, 3),
(58, 4),
(59, 4),
(60, 4),
(61, 4),
(62, 4),
(63, 4),
(64, 4),
(65, 4),
(66, 4),
(67, 4),
(68, 4),
(69, 4),
(70, 4),
(71, 4),
(72, 4),
(73, 5),
(74, 5),
(75, 5),
(76, 5),
(77, 5),
(78, 5),
(79, 5),
(80, 5),
(81, 5),
(82, 5),
(83, 5),
(84, 5),
(85, 5),
(86, 5),
(87, 5),
(88, 5),
(89, 5),
(90, 5),
(91, 5),
(92, 5),
(93, 5),
(94, 5),
(95, 5),
(96, 5),
(97, 5),
(98, 5),
(99, 5),
(100, 5),
(101, 6),
(102, 6),
(103, 6),
(104, 6),
(105, 6),
(106, 6),
(107, 6),
(108, 6),
(109, 6),
(110, 6),
(111, 6),
(112, 6),
(113, 6),
(114, 7),
(115, 7),
(116, 7),
(117, 7),
(118, 7),
(119, 7),
(120, 7),
(121, 7),
(122, 7),
(123, 7),
(124, 7),
(125, 7),
(126, 7),
(127, 7),
(128, 7),
(129, 8),
(130, 8),
(131, 8),
(132, 8),
(133, 8),
(134, 8),
(135, 8),
(136, 8),
(137, 8),
(138, 8),
(139, 8),
(140, 8),
(141, 8),
(142, 8),
(143, 8),
(144, 9),
(145, 9),
(146, 9),
(147, 9),
(148, 9),
(149, 9),
(150, 9),
(151, 9),
(152, 9),
(153, 9),
(154, 9),
(155, 9),
(156, 9);

INSERT INTO Answers (QuestionId, Payload, IsCorrect)
VALUES
(1, "5 341 meters", 0),
(1, "234 783 345 meters", 0),
(1, "149 597 870 700 meters", 1),
(1, "2 235 542 098 234 meters", 0),
(2, "Andromeda", 1),
(2, "Android", 0),
(2, "Cigar", 0),
(2, "Coffee Way", 0),
(2, "Whirlpool", 0),
(2, "Sombrero", 0),
(3, "Gas giant", 0),
(3, "Ice planet", 0),
(3, "River planet", 1),
(3, "Dwarf planet", 0),
(4, "Helium", 0),
(4, "Carbon dioxide", 0),
(4, "Hydrogen", 1),
(4, "Methane", 0),
(5, "Red giant", 0),
(5, "Yellow super giant", 0),
(5, "Blue dwarf", 0),
(5, "Red dwarf", 0),
(5, "Yellow main sequence", 1),
(6, "Polaris", 0),
(6, "Betelgeuse", 0),
(6, "Bellatrix", 0),
(6, "Sirius", 1),
(6, "Vega", 0),
(7, "Andromeda", 0),
(7, "Regulus", 0),
(7, "The astroid belt", 0),
(7, "Omega Centauri", 1),
(7, "Cassiopeia", 0),
(8, "Open cluster", 0),
(8, "Black hole", 0),
(8, "Brown dwarf", 1),
(8, "Pulsar", 0),
(8, "Exoplanet", 0),
(9, "Irregular", 0),
(9, "Dwarf elliptical", 0),
(9, "Spiral", 1),
(9, "Barred spiral", 0),
(9, "Elliptical", 0),
(10, "Space", 0),
(10, "Interstellar space", 1),
(10, "Intergalactic space", 0),
(10, "Outer space", 0),
(10, "Interplanetary space", 0),
(11, "It reaches us immediately", 0),
(11, "5 minutes", 0),
(11, "3 seconds", 0),
(11, "8 minutes", 1),
(11, "8 seconds", 0),
(12, "It is seen by us immediately", 0),
(12, "8 minutes", 0),
(12, "8 seconds", 0),
(12, "1 minutes and 3 seconds", 0),
(12, "1.3 seconds", 1),
(13, "The Moon", 0),
(13, "Titania", 0),
(13, "Charon", 0),
(13, "Titan", 0),
(13, "Ganymede", 1),
(14, "Outer", 0),
(14, "Sagittarius", 1),
(14, "Milky Way", 0),
(14, "Orion", 0),
(14, "Perseus", 0),
(15, "Hypernova", 1),
(15, "There is no stronger explosion", 0),
(15, "Big Bang", 0),
(15, "Nova", 0),
(15, "Ultranova", 0),
(16, "The Andromeda galaxy", 1),
(16, "Europe", 0),
(16, "Sagittarius", 0),
(16, "The Whirlpool Galaxy", 0),
(16, "Betelgeuse", 0),
(17, "Quasar", 0),
(17, "Gemini", 0),
(17, "Milky Way", 0),
(17, "Local", 1),
(17, "Virgo", 0),
(18, "A black hole's gravity acts as a lens and bends the light to create the illusion of five images forming a cross", 1),
(18, "There is no such thing as Einstein's Cross", 0),
(18, "Four galaxies were attracted to another, bigger galaxy from four different directions, and we see them preparing to collide", 0),
(19, "50 million", 0),
(19, "1 trillion", 0),
(19, "50 billion", 1),
(19, "80 million", 0),
(19, "15 billion", 0),
(20, "No, because the tidal force will always exceed the amount of stretching that your body can take", 0),
(20, "Yes, if it is an extremely small black hole", 0),
(20, "Yes, if it is an extremely large black hole", 1),
(21, "Open clusters", 0),
(21, "Elliptical galaxies", 0),
(21, "Quasars", 1),
(21, "Globular clusters", 0),
(21, "Pulsars", 0),
(22, "The Milky Way, of which we reside", 0),
(22, "M87, an elliptical galaxy in the Virgo Cluster", 1),
(22, "The Andromeda Galaxy, of the Local Cluster", 0),
(22, "The Sombrero Galaxy, of the Virgo Cluster", 0),
(22, "The Whirlpool Galaxy, a spiral galaxy of the Local Cluster", 0),
(23, "Betelgeuse", 0),
(23, "Regulus", 0),
(23, "Eta Carinae", 1),
(23, "Vega", 0),
(23, "Polaris", 0),
(24, "Reflection", 1),
(24, "No nebulae are blue in color", 0),
(24, "Emission", 0),
(24, "Dark", 0),
(24, "Orion", 0),
(25, "Animals", 1),
(25, "Fungi", 1),
(25, "Plants", 1),
(26, "Division", 1),
(26, "Phylum", 1),
(26, "Class", 1),
(31, "Cut and Clone", 0),
(31, "Transcription and Translation", 0),
(31, "Mitosis and Meiosis", 1),
(31, "Divide and Conquer", 0),
(28, "Petals", 1),
(28, "Seed coats to protect seeds", 1),
(28, "Fleshy fruit", 1),
(29, "Cycad", 0),
(29, "Gynko", 1),
(29, "Pine Tree", 0),
(30, "Circulatory", 0),
(30, "Muscular", 0),
(30, "Endocrine", 0),
(30, "Visionary", 0),
(27, "Antheridium", 1),
(27, "Xylem", 1),
(27, "Dicotyledon", 1),
(32, "True", 0),
(32, "False", 1),
(33, "True", 0),
(33, "False", 1),
(34, "Yes", 0),
(34, "No", 0),
(34, "Sometimes", 1),
(35, "Daisy", 0),
(35, "Moss", 1),
(35, "Pine Tree", 0),
(35, "All do", 0),
(36, "They don't need water to reproduce", 0),
(36, "They have seeds", 0),
(36, "Both are advantages", 1),
(37, "Artery, Vein, Hemoglobin", 0),
(37, "Roots, Stems, Leaves", 0),
(37, "Bacteria, Fungi, Algae", 1),
(37, "None of the above", 0),
(38, "Gallium", 1),
(38, "Bromine", 1),
(38, "Magnesium", 0),
(38, "Mercury", 1),
(39, "Tryptophan", 1),
(39, "Tyrosine", 1),
(39, "Leucine", 1),
(39, "Adenine", 0),
(40, "1 kilogram", 0),
(40, "250 grams", 1),
(40, "500 grams", 0),
(40, "Practically none", 0),
(41, "The glass will over flow as the ice turns to water.", 0),
(41, "The level of water in the glass will remain unchanged as the ice melts.", 0),
(41, "The water level will drop slightly as the ice melts.", 1),
(41, "I'll never find out because I'll drink the water or walk away before anything happens.", 0),
(42, "Arsenic", 0),
(42, "Antimony", 1),
(42, "Seaborgium", 0),
(42, "Tin", 0),
(42, "Samarium", 0),
(43, "Slightly acidic", 1),
(43, "Neutral", 0),
(43, "Milk does not have a pH", 0),
(43, "Strong acid", 0),
(43, "Strong basic", 0),
(44, "Tubulin", 0),
(44, "Collagen", 1),
(44, "Albumin", 0),
(44, "Keratin", 0),
(45, "Helium", 0),
(45, "Chlorine", 1),
(45, "Argon", 0),
(45, "Krypton", 0),
(46, "Protium", 1),
(46, "Deuterium", 0),
(46, "Tritium", 0),
(46, "Hydrogen only has one isotope", 0),
(47, "H2", 0),
(47, "H2O", 1),
(47, "O2", 0),
(47, "H2O2", 0),
(48, "Nobel", 0),
(48, "Mendel", 0),
(48, "Lavoisier", 0),
(48, "Mendeleev", 1),
(49, "Sulfur", 1),
(49, "Aluminium", 0),
(49, "Manganese", 0),
(49, "Beryllium", 0),
(50, "Carbon only", 0),
(50, "Carbon and hydrogen", 1),
(50, "Carbon and nitrogen", 0),
(50, "Carbon, hydrogen and oxygen", 0),
(51, "Gallium", 0),
(51, "Gold", 0),
(51, "Magnesium", 0),
(51, "Silver", 1),
(52, "A defined volume, but not a defined shape", 1),
(52, "A definite shape, but no defined volume", 0),
(52, "A definite volume and shape", 0),
(52, "No defined volume or shape ", 0),
(53, "Your brain", 0),
(53, "Your bones", 0),
(53, "Your skin", 0),
(53, "Your blood", 1),
(54, "6023", 0),
(54, "6.023 x 10^23", 1),
(54, "6.02 x 10^-23", 0),
(54, "3 x 10^8", 0),
(55, "A molecule", 0),
(55, "An anion", 0),
(55, "An isotope", 0),
(55, "A cation", 1),
(56, "Diffusion", 1),
(56, "Vapor pressure", 0),
(56, "Osmosis", 0),
(56, "Effusion", 0),
(57, "Solute", 1),
(57, "Colloid", 0),
(57, "Solvent", 0),
(57, "Sol", 0),
(58, "Slovakia", 0),
(58, "Hungary", 0),
(58, "Romania", 0),
(58, "Moldova", 0),
(59, "Western Australia", 1),
(59, "New South Wales", 0),
(59, "Queensland", 0),
(59, "Tasmania", 0),
(60, "Bataysk", 0),
(60, "Yerevan", 1),
(60, "Baku", 0),
(60, "Tbilisi", 0),
(61, "White Sea", 0),
(61, "Norwegian Sea", 0),
(61, "Bering Sea", 1),
(61, "Beaufort Sea", 0),
(62, "North Pacific Ocean", 0),
(62, "Mediterranean Sea", 1),
(62, "Arctic Ocean", 0),
(62, "South Atlantic Ocean", 0),
(63, "Tanzania", 0),
(63, "Democratic Republic of Congo", 0),
(63, "Kenya", 1),
(63, "South Sudan", 0),
(64, "Israel", 1),
(64, "Egypt", 0),
(64, "Jordan", 0),
(64, "Turkey", 0),
(65, "Kazakhstan", 1),
(65, "Kyrgyzstan", 0),
(65, "Uzbekistan", 0),
(65, "Turkmenistan", 0),
(66, "Spain", 0),
(66, "France", 1),
(66, "United Kingdom", 0),
(66, "Germany", 0),
(67, "South Africa", 1),
(67, "Brasil", 0),
(67, "Uganda", 0),
(67, "Bolivia", 0),
(68, "Tonga", 0),
(68, "Fiji", 0),
(68, "United States", 0),
(68, "New Zealand", 1),
(69, "One degree west", 0),
(69, "Five degrees west", 0),
(69, "Three degrees west", 1),
(69, "Seven degrees west", 0),
(70, "Cape Cornwall", 1),
(70, "Cape Coral", 0),
(70, "Cape Canaveral", 0),
(70, "Cape Horn", 0),
(71, "Italy", 1),
(71, "Canada", 0),
(71, "South Africa", 0),
(71, "Russia", 0),
(72, "Dneiper", 0),
(72, "Danube", 0),
(72, "Ural", 0),
(72, "Rhine", 1),
(73, "Cotton", 1),
(73, "Rice", 0),
(73, "Tobacco", 0),
(73, "Indigo", 0),
(74, "United Nations", 0),
(74, "Public Works Administration", 0),
(74, "Marshall Plan", 0),
(74, "Manhattan Project", 1),
(75, "Anglicans", 0),
(75, "Separatists", 1),
(75, "Lutherans", 0),
(75, "Huguenots", 0),
(76, "Abraham Lincoln", 0),
(76, "James Madison", 0),
(76, "William Henry Harrison", 1),
(77, "Crete", 0),
(77, "Sardinia", 0),
(77, "Sicily", 0),
(77, "Corsica", 1),
(78, "Vladimir Putin", 0),
(78, "Mikhail Gorbachov", 1),
(78, "Leonid Brezhnev", 0),
(78, "Joseph Stalin", 0),
(79, "Mesopotamia", 0),
(79, "Aztecs", 0),
(79, "Egypt", 1,
(79, "Persia", 0),
(80, "Muhatma Gandhi", 1),
(80, "Muhammad Ali Jinnah", 0),
(80, "Akesh Chopra", 0),
(80, "Jawaharlal Nehru", 0),
(81, "Alexander the Great", 0),
(81, "Nicanor", 0),
(81, "Hannibal", 1),
(81, "Odysseus", 0),
(82, "John Burhoyne", 0),
(82, "Charles Cornwallis", 1),
(82, "Robert Clive", 0),
(82, "James Wolfe", 0),
(83, "France", 0),
(83, "England", 0),
(83, "Spain", 1),
(83, "Portugal", 0),
(84, "1923", 0),
(84, "1938", 0),
(84, "1917", 0),
(84, "1914", 1),
(85, "France", 0),
(85, "Germany", 0),
(85, "Austria", 1),
(85, "Hungary", 0),
(86, "1973", 0),
(86, "Austin", 0),
(86, "Dallas", 1),
(86, "1958", 0),
(87, "Andrew Jackson", 1),
(87, "Arthur Wellsley", 0),
(87, "Otto von Bismarck", 0),
(87, "Napoleon", 0),
(88, "Bull Halsey", 0),
(88, "George Patton", 0),
(88, "Douglas MacArthur", 1),
(88, "Omar Bradley", 0),
(89, "1970s", 0),
(89, "1950s", 1),
(89, "1920s", 0),
(89, "1960s", 0),
(90, "France", 0),
(90, "Russia", 0),
(90, "England", 1),
(90, "Norway", 0),
(91, "France", 0),
(91, "Austria", 0),
(91, "Italy", 0),
(91, "England", 1),
(92, "Johannes Gutenberg", 1),
(92, "Benjamin Franklin", 0),
(92, "Sir Isaac Newton", 0),
(92, "Marthin Luther", 0),
(93, "The White Death", 0),
(93, "The Black Plague", 0),
(93, "Smallpox", 0),
(93, "The Bubonic Plague", 1),
(94, "Italy and Carthage", 0),
(94, "England and Germany", 0),
(94, "France and England", 0),
(94, "Spain and France", 0),
(95, "Marcus Aurelius", 0),
(95, "Hadrian", 1),
(95, "Nero", 0),
(95, "Augustus", 0),
(96, "Martin Luther", 1),
(96, "Saint Augustus", 0),
(96, "Henry David Thoreau", 0),
(96, "Voltaire", 0),
(97, "Broadway", 0),
(97, "Oxford University Theatre", 0),
(97, "The Globe", 1),
(97, "The London Palladium", 0),
(98, "Vietnam", 0),
(98, "Laos", 0),
(98, "Cambodia", 1),
(98, "China", 0),
(99, "Hannibal", 0),
(99, "Julius Caesar", 0),
(99, "William the Conqueror", 0),
(99, "Atilla the Hun", 1),
(100, "Magellan", 0),
(100, "Cook", 0),
(100, "Marco Polo", 1),
(100, "Sir Francis Drake", 0);